name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build English site
        run: bundle exec jekyll build -d ./generated/en --source ./blog/en --config _config_en.yml

      - name: Build Chinese site
        run: bundle exec jekyll build -d ./generated/zh --source ./blog/zh --config _config_zh.yml

      - name: Copy sites
        run: |
          mkdir -p en
          mkdir -p zh
          cp -r ./generated/en/* en
          cp -r ./generated/zh/* zh

      - name: Copy index.html to root
        run: cp blog/index.html ./generated/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./generated
