name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build English site
        run: bundle exec jekyll build -d ./generated/en --source ./blog/en --config _config_en.yml

      - name: Build Portuguese site
        run: bundle exec jekyll build -d ./generated/pt --source ./blog/pt --config _config_pt.yml

      - name: Copy sites
        run: |
          mkdir -p en
          mkdir -p pt
          cp -r ./generated/en/* en
          cp -r ./generated/pt/* pt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
